// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShredleApi.Data;

#nullable disable

namespace ShredleApi.Migrations
{
    [DbContext(typeof(ShredleDbContext))]
    [Migration("20250603121450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShredleApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("SoloId")
                        .HasColumnType("integer")
                        .HasColumnName("solo_id");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.HasIndex("SoloId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("ShredleApi.Models.Solo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("artist");

                    b.Property<double>("EndTimeClip1")
                        .HasColumnType("double precision")
                        .HasColumnName("end_time_clip1");

                    b.Property<double>("EndTimeClip2")
                        .HasColumnType("double precision")
                        .HasColumnName("end_time_clip2");

                    b.Property<double>("EndTimeClip3")
                        .HasColumnType("double precision")
                        .HasColumnName("end_time_clip3");

                    b.Property<double>("EndTimeClip4")
                        .HasColumnType("double precision")
                        .HasColumnName("end_time_clip4");

                    b.Property<string>("Guitarist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guitarist");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hint");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("spotify_id");

                    b.Property<double>("StartTimeClip1")
                        .HasColumnType("double precision")
                        .HasColumnName("start_time_clip1");

                    b.Property<double>("StartTimeClip2")
                        .HasColumnType("double precision")
                        .HasColumnName("start_time_clip2");

                    b.Property<double>("StartTimeClip3")
                        .HasColumnType("double precision")
                        .HasColumnName("start_time_clip3");

                    b.Property<double>("StartTimeClip4")
                        .HasColumnType("double precision")
                        .HasColumnName("start_time_clip4");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("solos", (string)null);
                });

            modelBuilder.Entity("ShredleApi.Models.Game", b =>
                {
                    b.HasOne("ShredleApi.Models.Solo", "Solo")
                        .WithMany("Games")
                        .HasForeignKey("SoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solo");
                });

            modelBuilder.Entity("ShredleApi.Models.Solo", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
